### ISSUE TITLE
DataGrid throws DOMException: Node.removeChild when using onCellPrepared + editCellComponent + boolean value

### ISSUE THREAD

**Issue by danieleff** [DevExpress/devextreme-react#451]
# Bug Report

**Package versions:**

    devexteme version: 20.1.7
    devextreme-react version: 20.1.7

**Steps to reproduce:**

The following code:
```
<DataGrid onCellPrepared={() => {}} dataSource={[{a: true}]} >
    <Editing allowUpdating mode="cell" />
    <Column dataField="a" editCellComponent={() => <div></div>} />
</DataGrid>
<button onClick={() => this.setState({})}>Click</button>
```
Click the button

**Current behavior:**

Throws Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node
The above error occurred in the <editCellComponent> component:
    in editCellComponent (created by TemplatesRenderer)
    in TemplateWrapper (created by TemplatesRenderer)
    in TemplatesRenderer (created by DataGrid)
    in div (created by DataGrid)
    ...

**Expected behavior:**

Clicking does not thow error

**Screenshots:**

N/A

The code was working in devextreme@19.2.7, but throws error in devextreme@19.2.8+ versions.

**Comment by pgrodrigues** [comment]
Any update on this? I also get this exact error but I'm not able to reproduce it consistently, it only happens sometimes.

In my case, I do not use editCellComponent but it seems to be triggered once I set a state via useState hook from inside onContentReady. I have many columns using cellRender and headerCellRender.

```
index.js:1 The above error occurred in the <TemplateWrapper> component:

    at TemplateWrapper (http://localhost:3000/static/js/0.chunk.js:41614:24)
    at TemplatesRenderer (http://localhost:3000/static/js/0.chunk.js:41975:43)
    at div
    at DataGrid (http://localhost:3000/static/js/0.chunk.js:42212:43)
```
```
react-dom.development.js:10307 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLBodyElement.removeChild (<anonymous>)
    at removeChildFromContainer (http://localhost:3000/static/js/0.chunk.js:314207:19)
    at unmountHostComponents (http://localhost:3000/static/js/0.chunk.js:324998:13)
    at commitDeletion (http://localhost:3000/static/js/0.chunk.js:325051:9)
    at commitMutationEffects (http://localhost:3000/static/js/0.chunk.js:327092:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:307785:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:307834:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:307894:35)
    at commitRootImpl (http://localhost:3000/static/js/0.chunk.js:326813:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:363455:16)
    at runWithPriority$1 (http://localhost:3000/static/js/0.chunk.js:315191:14)
    at commitRoot (http://localhost:3000/static/js/0.chunk.js:326686:7)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/0.chunk.js:326028:7)
    at http://localhost:3000/static/js/0.chunk.js:315245:30
    at unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:363455:16)
    at runWithPriority$1 (http://localhost:3000/static/js/0.chunk.js:315191:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/0.chunk.js:315240:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/0.chunk.js:315228:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/0.chunk.js:325592:13)
    at Object.enqueueForceUpdate (http://localhost:3000/static/js/0.chunk.js:316403:9)
    at TemplatesRenderer.push../node_modules/react/cjs/react.development.js.Component.forceUpdate (http://localhost:3000/static/js/0.chunk.js:354701:20)
    at http://localhost:3000/static/js/0.chunk.js:41990:13
    at deferExecute (http://localhost:3000/static/js/0.chunk.js:56880:18)
    at deferUpdate (http://localhost:3000/static/js/0.chunk.js:56913:10)
    at deferExecute (http://localhost:3000/static/js/0.chunk.js:56899:70)
    at deferUpdate (http://localhost:3000/static/js/0.chunk.js:56913:10)
    at deferExecute (http://localhost:3000/static/js/0.chunk.js:56899:70)
    at deferRender (http://localhost:3000/static/js/0.chunk.js:56907:10)
    at inheritor._fireChanged (http://localhost:3000/static/js/0.chunk.js:122193:35)
    at inheritor._fireChanged (http://localhost:3000/static/js/0.chunk.js:130120:16)
    at inheritor._fireChanged (http://localhost:3000/static/js/0.chunk.js:49507:21)
    at inheritor.updateItems (http://localhost:3000/static/js/0.chunk.js:122179:16)
    at Array.<anonymous> (http://localhost:3000/static/js/0.chunk.js:121610:22)
    at Object._promise.<computed> [as done] (http://localhost:3000/static/js/0.chunk.js:58710:17)
    at inheritor._handleDataChanged (http://localhost:3000/static/js/0.chunk.js:121585:86)
    at inheritor._handleDataChanged (http://localhost:3000/static/js/0.chunk.js:138479:25)
    at inheritor._handleDataChanged (http://localhost:3000/static/js/0.chunk.js:49507:21)
    at Callback.that._dataChangedHandler (http://localhost:3000/static/js/0.chunk.js:121325:18)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore (http://localhost:3000/static/js/0.chunk.js:56696:44)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith (http://localhost:3000/static/js/0.chunk.js:56765:12)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire (http://localhost:3000/static/js/0.chunk.js:56775:8)
    at inheritor._handleDataChanged (http://localhost:3000/static/js/0.chunk.js:123186:22)
    at fireChanged (http://localhost:3000/static/js/0.chunk.js:143613:5)
    at processChanged (http://localhost:3000/static/js/0.chunk.js:143676:7)
    at inheritor.handleDataChanged (http://localhost:3000/static/js/0.chunk.js:144075:11)
    at inheritor._handleDataChanged (http://localhost:3000/static/js/0.chunk.js:142327:37)
    at inheritor._handleDataChanged (http://localhost:3000/static/js/0.chunk.js:49507:21)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore (http://localhost:3000/static/js/0.chunk.js:56696:44)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith (http://localhost:3000/static/js/0.chunk.js:56765:12)
    at EventsStrategy.value (http://localhost:3000/static/js/0.chunk.js:51841:19)
removeChildFromContainer @ react-dom.development.js:10307
unmountHostComponents @ react-dom.development.js:21294
commitDeletion @ react-dom.development.js:21347
commitMutationEffects @ react-dom.development.js:23407
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23121
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueForceUpdate @ react-dom.development.js:12504
push../node_modules/react/cjs/react.development.js.Component.forceUpdate @ react.development.js:384
(anonymous) @ templates-renderer.js:46
deferExecute @ common.js:66
deferUpdate @ common.js:91
deferExecute @ common.js:81
deferUpdate @ common.js:91
deferExecute @ common.js:81
deferRender @ common.js:87
_fireChanged @ ui.grid_core.data_controller.js:802
_fireChanged @ ui.grid_core.focus.js:488
(anonymous) @ class.js:24
updateItems @ ui.grid_core.data_controller.js:791
(anonymous) @ ui.grid_core.data_controller.js:310
_promise.<computed> @ deferred.js:51
_handleDataChanged @ ui.grid_core.data_controller.js:292
_handleDataChanged @ ui.grid_core.selection.js:469
(anonymous) @ class.js:24
that._dataChangedHandler @ ui.grid_core.data_controller.js:78
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire @ callbacks.js:85
_handleDataChanged @ ui.grid_core.data_source_adapter.js:494
fireChanged @ ui.grid_core.virtual_scrolling_core.js:216
processChanged @ ui.grid_core.virtual_scrolling_core.js:267
handleDataChanged @ ui.grid_core.virtual_scrolling_core.js:603
_handleDataChanged @ ui.grid_core.virtual_scrolling.js:158
(anonymous) @ class.js:24
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
value @ events_strategy.js:65
_fireChanged @ data_source.js:249
(anonymous) @ data_source.js:255
(anonymous) @ deferred.js:54
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire @ callbacks.js:85
_DeferredObj.<computed> @ deferred.js:108
(anonymous) @ deferred.js:43
resolvePendingDeferred @ data_source.js:465
_processStoreLoadResult @ data_source.js:487
(anonymous) @ data_source.js:449
_promise.<computed> @ deferred.js:51
handleSuccess @ data_source.js:447
(anonymous) @ deferred.js:54
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire @ callbacks.js:85
_DeferredObj.<computed> @ deferred.js:108
(anonymous) @ abstract_store.js:77
_promise.<computed> @ deferred.js:51
(anonymous) @ abstract_store.js:76
(anonymous) @ deferred.js:54
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire @ callbacks.js:85
_DeferredObj.<computed> @ deferred.js:108
(anonymous) @ deferred.js:43
(anonymous) @ custom_store.js:254
(anonymous) @ deferred.js:54
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire @ callbacks.js:85
_DeferredObj.<computed> @ deferred.js:108
(anonymous) @ deferred.js:121
Promise.then (async)
fromPromise @ deferred.js:120
invokeUserLoad @ custom_store.js:90
_loadImpl @ custom_store.js:253
(anonymous) @ class.js:24
load @ abstract_store.js:64
_loadFromStore @ data_source.js:455
loadTask @ data_source.js:307
callback @ common.js:38
setTimeout (async)
executeAsync @ common.js:47
(anonymous) @ data_source.js:316
exec @ queue.js:29
add @ queue.js:52
load @ data_source.js:314
load @ ui.grid_core.virtual_scrolling.js:111
loadCore @ ui.grid_core.virtual_scrolling_core.js:275
load @ ui.grid_core.virtual_scrolling_core.js:511
load @ ui.grid_core.virtual_scrolling.js:180
(anonymous) @ class.js:24
(anonymous) @ ui.grid_core.data_controller.js:392
_promise.<computed> @ deferred.js:51
_promise.always @ deferred.js:61
_loadDataSource @ ui.grid_core.data_controller.js:390
(anonymous) @ class.js:24
_loadDataSource @ ui.grid_core.selection.js:435
(anonymous) @ class.js:24
_refreshDataSource @ data_helper.js:29
_refreshDataSource @ ui.grid_core.state_storing.js:216
(anonymous) @ class.js:24
_refreshDataSource @ ui.grid_core.virtual_scrolling.js:652
(anonymous) @ class.js:24
reset @ ui.grid_core.data_controller.js:115
applyState @ ui.grid_core.state_storing.js:179
state @ ui.grid_core.state_storing.js:126
(anonymous) @ class.js:24
(anonymous) @ ui.grid_core.state_storing_core.js:116
(anonymous) @ deferred.js:54
push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore @ callbacks.js:25
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith @ callbacks.js:77
push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire @ callbacks.js:85
_DeferredObj.<computed> @ deferred.js:108
(anonymous) @ deferred.js:121
Promise.then (async)
fromPromise @ deferred.js:120
load @ ui.grid_core.state_storing_core.js:111
optionChanged @ ui.grid_core.state_storing_core.js:142
(anonymous) @ class.js:24
(anonymous) @ ui.grid_core.modules.js:336
each @ iterator.js:34
callModuleItemsMethod @ ui.grid_core.modules.js:335
_optionChanged @ ui.data_grid.base.js:124
(anonymous) @ class.js:24
_notifyOptionChanged @ component.js:216
(anonymous) @ component.js:95
value @ option_manager.js:79
value @ option_manager.js:112
value @ index.js:200
option @ component.js:325
OptionsManager._setValue @ options-manager.js:168
OptionsManager.update @ options-manager.js:73
ComponentBase.componentDidUpdate @ component-base.js:79
commitLifeCycles @ react-dom.development.js:20684
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
handleContentReady @ MyGrid.js:174                                        <---------------------------------------------
(anonymous) @ options-manager.js:142
execute @ action.js:185
```

**Comment by onebalaban** [comment]
Hi,

If the issue still appears, we need to reproduce it on our side to find its cause. Please share a [test project](https://community.devexpress.com/blogs/ctodx/archive/2009/01/08/a-request-for-simple-example-programs.aspx) to demonstrate this behavior. We'll research the issue and do our best to find a solution. You can use our [React template](https://github.com/DevExpress/devextreme-react-template) to create this project.
